### ISSUE TITLE
Access Blocked Authorization Error

### ISSUE THREAD

**Issue by blamechris** [openbridge/ob_google-bigquery#3]
Whenever I attempt to run through the steps to get this running in a docker container, I get a Error 400: invalid_request with the google auth telling me:

The version of the app you're using doesn't include the latest security features to keep you protected. Please make sure to download from a trusted source and update to the latest, most secure version.

Do you have any workarounds for this?

**Comment by tspicer** [comment]
Hi,

Can you provide more details on your steps? Did you build or pull the image?

**Comment by blamechris** [comment]
Hey,

I built the image, then ran this command:
`docker run -t -i --name gcloud-config openbridge/ob_google-bigquery gcloud init`

And then it pops up with a URL to copy paste, but then it results in the 400 error whenever I do so.

**Comment by tspicer** [comment]
Did you try following the instructions in using a local Auth file?

**Comment by blamechris** [comment]
I did, but I'll try doing it again and see if that's the issue.

**Comment by blamechris** [comment]
I remade the auth file and it corrected my issue, thanks for the help.
